[
    "utils/String.js",
    "utils/Date.js",
    "utils/Persist.js",
    "utils/Hashes.js",
    "utils/Overlay.js",
    "utils/JSON.js",
    "utils/Arrays.js",
    "utils/DOM.js",
    "utils/Notification.js",
    "utils/Objects.js"
]